name: Update User Interests
on:
#  schedule:
#    - cron: '0 0 * * 6' # Run every Saturday
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: read

jobs:
  analyze-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Auth with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Run Analysis Script
        run: |
          npm install tsx
          npx tsx scripts/process-interests.ts